### ISSUE TITLE
Cloudboost SDK supported browser

### ISSUE THREAD

**Issue by hdriqi** [CloudBoost/cloudboost#102]
What is the oldest browser supported by cloudboost SDK?

I am using old zenfone 5 phone, using its official browser, cloudboost does not working. 
I try to do alert(CB), but nothing happened.

**Comment by nawazdhandala** [comment]
I think we support all the major browsers like IE, Firefox, Chrome, Safari etc on Phones. Which browser is this?

On 11 Jan 2017, 10:43 PM +0530, Rahmat Albariqi <notifications@github.com>, wrote:

What is the oldest browser supported by cloudboost SDK?

I am using old zenfone 5 phone, using its official browser, cloudboost does not working.
I try to do alert(CB), but nothing happened.

**Comment by hdriqi** [comment]
@nawazdhandala it doesnt even have a name. lol. 
Nevermind, I think most people in this world dont use that browser.
