### ISSUE TITLE
Save file from BLOB

### ISSUE THREAD

**Issue by hdriqi** [CloudBoost/cloudboost#105]
So I am trying to save an image into cloudboost files using example code:
```
var imgBlob = new Blob([
  'This is the content of by document blob'
  ], {
  type : 'image/png'
});
var file = new CB.CloudFile(imgBlob);
file.save({
  success: function(file) {
      console.log(file.URL);
  }, error: function(err) {
      //error in uploading File
  }, uploadProgress : function(percentComplete){
        //upload progress.
  }
});
```

The file are uploaded successfully, and also I got the URL. but, when I open the URL it give 500 error ( unauthorized ). 
What I want to do is simply store my image, and get the URL.

**Comment by nawazdhandala** [comment]
Let us check and get back.

**Comment by hdriqi** [comment]
@nawazdhandala looks like I found the problem. The file name must present and must have the same extension as the MIME content type. Maybe you could add this in to the documentation. Thanks!

**Comment by nawazdhandala** [comment]
Sure, I'll get this through.
