### ISSUE TITLE
Offline story [3-way merge?]

### ISSUE THREAD

**Issue by anilgulecha** [CloudBoost/cloudboost#110]
Hi, I've come across cloudboost in my search for a nodejs based DBaaS.

The landing page talks about offline features, but it looks like that largely refers to the offline cache feature? Is there a developer story for a 3 way merge? (two offline clients make independent changes to the same object).

In my usecase it would be fine if deciding on the merge required writing a custom function which would take the 3 data-points as input, but the server would still be responsible for sending merge conflict resolutions to the actual nodes.

Any docs/thoughts around this?

**Comment by nawazdhandala** [comment]
We're working on the Offline Sync feature and that's expected to be launched in about a month from now.

**Comment by nawazdhandala** [comment]
Done! :)

**Comment by anilgulecha** [comment]
Great, I'll look for the docs.

**Comment by anilgulecha** [comment]
@nawazdhandala So I looked at https://tutorials.cloudboost.io/en/offlinesync/localstore , but it seems to only suggest 1-1 sync. How are merge conflicts handled?

**Comment by nawazdhandala** [comment]
@anilgulecha I'm sorry, I missed this. Yes its 1-1 right now. What that means is client which syncs later wins (However, only pieces of object they've modified will be updated and not the whole object). Can you please explain the strategy you need to resolve conflicts? Is it something like - Client which updates a piece of data the most latest wins?
