### ISSUE TITLE
CloudObject Notifications on the client does not fire when an object is updated from the server

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/cloudboost#155]
I have strange issue with cloudObject notifications. They don't work when row is updated from script running on server. Let me explain - I have frontend that subscribes into notifications, queue and script. Script watches in interval for messages in queue and when there is message it takes it and starts processing. When processing it updates progress field in cloudboost from time to time when steps are finished. Frontend watches for changes in this field and shows progress for user. Now the issue - I can run script from my local machine, I can even update field in cloudboost dashboard manually - frontend will get notifications but when I try to run script on remote server changes in database are visible but object notification is not triggered. I've tried 2 different servers, the same configuration as I used on localhost and notifications are not triggered. Are there some limitations for these notifications not mentioned in docs or maybe you have an idea what I am missing here?

**Comment by aqum** [comment]
Here are the snippets that I used to test the case and make sure that it is not problem with my code:

Backend (node v6.10.0, cloudboost sdk package v1.3.9)
```
const CB = require('cloudboost');
CB.CloudApp.init('...', '...');

const query = new CB.CloudQuery('videoMeta');
query.equalTo('youtubeId', 'pslN7pLwvmQ');
query.findOne({
  success: obj => {
    console.log('fetched');
    obj.set('processingStep', 'gathering-data');
    obj.save({
      success: () => console.log('saved'),
      error: err => console.log('saving error', err),
    });
  },
  error: err => console.log('fetching err', err),
});
```

Frontend (chrome 57):
```
<script src="https://cloudboost.io/js-sdk/cloudboost.js"></script>
<script>
CB.CloudApp.init('...', '...');
console.log('init');
CB.CloudObject.on('videoMeta', 'updated', function(obj){
   console.log(obj.get('processingStep'));
});
</script>
```

**Comment by nawazdhandala** [comment]
Any updates on this? Did you get a chance to work on this?

**Comment by aqum** [comment]
I've set up droplet on digital ocean and fresh app on cloudboost.io but still the same results (notification doesn't work when object is updated from server but works when changing value from dashboard) - so this is not about server configuration.

You mentioned on slack that you managed to get it to work with heroku. How you ran this, what was your steps? I upload script to server, serve index.html locally and run script on server.
