### ISSUE TITLE
Multi-tenant apps Question?

### ISSUE THREAD

**Issue by kethan** [CloudBoost/cloudboost#161]
Hi, 

How do I create multi-tenant apps using cloudboost. Let's say I want to create a Marketplace app like amazon or Flipkart Or Apps by organization. How can I have different user and roles how can I group them? How do I structure the app? 

There is CloudUsers, CloudRoles and ACL but no grouping?

Example : 

You have multiple stores.

Each store can have multiple Store Users.

Each Store User can have one or more Store Roles (eg, Store Manager, Store Administrator).

Only Store Managers of Store A can create and edit products for Store A.

Only Store Managers of Store B can create and edit products for Store B.

Only Store Administrators of Store A can download transaction details for Store A.

Only Store Administrators of Store B can download transaction details for Store B.

**Comment by nawazdhandala** [comment]
You have multiple stores.
You can create a table for Stores and have as many stores in them. 

Each store can have multiple Store Users.
Use User table for this, and in the store table have ACL's pointed to only those users you want to give access to. Click [here](https://tutorials.cloudboost.io/en/security/acl) to read more about ACL's. 

Each Store User can have one or more Store Roles (eg, Store Manager, Store Administrator).
Use Role table for this. Check https://tutorials.cloudboost.io/en/security/roles

Only Store Managers of Store A can create and edit products for Store A.
Only Store Managers of Store B can create and edit products for Store B.
Only Store Administrators of Store A can download transaction details for Store A.
Only Store Administrators of Store B can download transaction details for Store B.

For all of these, You can use ACL's (https://tutorials.cloudboost.io/en/security/acl) to give access to particular user and particular roles.

**Comment by kethan** [comment]
Hi,

I am sorry that partially answered my question. How about I creating different organization or tenant for the app they will have shared users and roles right? 

Org1 - Separate users and roles.
Org2 - Separate users and roles.
etc

**Comment by nawazdhandala** [comment]
I think then you would have org 1 &2 in organisation table and then use User and Roles give them access to those Organisations via ACL's. 

Let me know if this helps.

**Comment by kethan** [comment]
Is it like can I have Users and Roles specific to Org1 Org2 etc. What if I register a user via local or social can I map that to specific Organization?

Can you just give me an example How would I create that Org table?

**Comment by kethan** [comment]
any idea?

**Comment by nawazdhandala** [comment]
Yes, you can. You just need to edit the ACL's in Organization Object with the User or Role you want to add.

**Comment by kethan** [comment]
Ok thank you @nawazdhandala

**Comment by kethan** [comment]
@nawazdhandala sorry but I have 1 question won't the user in a users table is common for the whole application right? How do I have 1 username **raj** with a password  **something** for org1 and the same user signs for org2 with the same username **raj** with different password **somethingelse** won't this conflict in users table?

**Comment by nawazdhandala** [comment]
In this case - you have two solutions: 
 - Have one user raj with one password login to any of the organisation. 
If you have two separate user with two org then, you can prefix the org name to username like org1-raj, and when the user signs in you can send the request with the prefixed name. 

Let me know if this helps.

**Comment by kethan** [comment]
@nawazdhandala Thanks now I understood. :) :+1:
