### ISSUE TITLE
Running cloudboost server

### ISSUE THREAD

**Issue by sumanindusnet** [CloudBoost/cloudboost#166]
I am running cloudboost without Docker. When running node server.js Cluster Key, Secure Key are showing on console after that it getting error
![untitled](https://cloud.githubusercontent.com/assets/13829449/25181791/4e58ab88-2530-11e7-8c92-be35bb4ded6a.png)
Registering Cluster...
Cluster registration failed.

**Comment by ritishgumber** [comment]
done
