### ISSUE TITLE
Accept Relations (and list of relations) like in these forms. 

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/cloudboost#176]
obj.set("relation",{"id":"9boEnOvY"});

or

obj.set("relation",{"_id":"9boEnOvY"});

or 

obj.set("relation","9boEnOvY");

**Comment by nawazdhandala** [comment]
When I set any of these requests from SDK. It should work instead of throwing an error. The changes should happen in backend,

**Comment by ritishgumber** [comment]
done
