### ISSUE TITLE
CloudBoost GUI/Front end?

### ISSUE THREAD

**Issue by blacksector** [CloudBoost/cloudboost#2]
Is there a front end on cloudboost? Or can there be one written?

**Comment by nawazdhandala** [comment]
Yes there is one at CloudBoost.io (Hosted and Managed Service). Its not open source. We have complete open source API's and you can build any kind of frontend on top of it. Let me know if this helps.

**Comment by blacksector** [comment]
I see, well do you guys maybe have a list of all the possible API commands? Or a list of things like how to create, delete or such? :) Thank you!

**Comment by nawazdhandala** [comment]
We have a REST API (We're still working on a documentation for it), but if you're building a Web UI then JS SDK will do, that's exactly how we run the web UI at CloudBoost as well.

**Comment by blacksector** [comment]
By web ui you mean an application? Or literally the control panel at cloudboost.io? 

And I see, so the REST API is in documentation, great I'll just wait, thank you! After that it will be a lot easier to understand how to create apps and manage them :) Thanks!

**Comment by nawazdhandala** [comment]
Control Panel at CloudBoost. :) I have opened an issue #3 . I'll close this thread. If you want to contribute to the documentation. You can check this repo out : https://github.com/CloudBoost/tutorial

Thank you so much for understanding.
