### ISSUE TITLE
Delete operations reject request body

### ISSUE THREAD

**Issue by egimaben** [CloudBoost/cloudboost#20]
I have observed this issue with common Java http-client libraries. When the http method is `delete`, then a request body is not expected and an error is thrown when there is one. Am not sure at all about other programming languages but I think the issue cuts across.
All **CloudBoost  ** `delete` APIs pass critical data in the request body by design. Can something be done about this on the backend?

**Comment by nawazdhandala** [comment]
Thanks for this Ben. Can you also raise a separate issue for the other thing we talked about.

**Comment by egimaben** [comment]
Trying one more approach before opening an issue
