### ISSUE TITLE
MandrillApp bridge

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/cloudboost#21]
It would be nice to provide a bridge to send emails using Cloudboost api. For example (javascript):

`CB.Mandrill.send(templateName, tos, vars)`

Now that mandrill api key can be configured in dashboard, my client app don't need to know anything about mandrill. 

With a good documentation of how to use send() method, it could be a nice feature.

Thanks!

**Comment by nawazdhandala** [comment]
This is on low priority for now. We'll be working on this after we get PushNotifications done. :) Let me know if this helps.

**Comment by gabrielAnglada** [comment]
Ok thanks! But please, when Push Notifications work, increase the priority of this :)

Regards

**Comment by nawazdhandala** [comment]
We definitely will. :)

**Comment by gabrielAnglada** [comment]
Hi Nawaz, I have already implemented Mandrill in my app. It is a very easy integration and actually I think that is not necessary to do this urgently. Your decision.

Thanks!
