### ISSUE TITLE
One folder with all the examples using cloudboost

### ISSUE THREAD

**Issue by norbertfuhs** [CloudBoost/cloudboost#211]
Hi I find it a little bit frustating that there is not one single folder with all the examples in it.. also a complete online tutorial building an little app with node.js would be great for starters..

**Comment by nawazdhandala** [comment]
Thank you for letting us know. We’ll have someone assigned to work on this and make this experience a LOT better than what it is now.

On 28 Jun 2017, 11:59 AM -0400, Norbert Fuhs <notifications@github.com>, wrote:

Hi I find it a little bit frustating that there is not one single folder with all the examples in it.. also a complete online tutorial building an little app with node.js would be great for starters..
