### ISSUE TITLE
3rd Party Auth / Facebook / Google

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/cloudboost#23]

**Comment by karol-depka** [comment]
+1

**Comment by gabrielAnglada** [comment]
+1

**Comment by nawazdhandala** [comment]
Thank you for +1. We'll work on this in about a week when Push Notifications are completed.

**Comment by nawazdhandala** [comment]
This is being worked on right now. Expected launch, in about 15 days.

**Comment by nawazdhandala** [comment]
This is done! :) Please check App Settings in CloudBoost Dashboard. :)
