### ISSUE TITLE
CloudNotification Security Issue ( important )

### ISSUE THREAD

**Issue by DevMoustache2** [CloudBoost/cloudboost#239]
I have a application built in Cloudbost that uses the Real Time notification.  (CloudNotification)

If I open the "inspect menu" from browser (tested on chrome), and go to Websocket monitor I can see every information in real time of anything being created/updated/deleted on database.

I'm with a client-side configurated with the client key (a website), and all my objects created by my server-side have the ACL set to "don't enable public read and write", but the information of the objects still are visible trough Websocket monitor.

Here is a example of my objects creation:

var objCupom = new CB.CloudObject('CupomFiscal');
objCupom.ACL = new CB.ACL();
objCupom.ACL.setPublicReadAccess(false);
objCupom.ACL.setPublicWriteAccess(false);
objCupom.save({success: function(){console.log('saved')}});

And here is the screenshot of WS Monitor on Chrome:

![erro](https://user-images.githubusercontent.com/31076114/29988193-56cfcb80-8f42-11e7-82bb-91f7ffd532b2.png)

Can you guys tell me if this is a issue or a misconfiguration?

Thanks

**Comment by shubhamqweasd** [comment]
@DevMoustache2 , thanks for pointing out this issue , we have fixed this issue now. 
Please update the sdk to the latest version, and that should fix it on your end.

Thanks
