### ISSUE TITLE
cannot attach services

### ISSUE THREAD

**Issue by HoseinGhanbari** [CloudBoost/cloudboost#245]
Hello ! 
I get the following error when trying to `node server.js`
MongoDB server version: 3.4.7
Node version: v6.11.3
NPM version: v5.4.1
Microsoft Windows 10 Enterprise
```
FATAL : Cannot attach services
function _sendNotification(appId, res, reqType, ) {
Attach API's
Failed to attach API's because services not loaded properly.
attachDbDisconnectApi..
attachCronJobs..
Secure Key : 8942a599-2147-4cd8-9920-ee3cb0738313
Registering Cluster...
Cluster Key : 649a28a6-85ba-430e-a11e-6c2e562937f9
```

**Comment by itsMagondu** [comment]
Got the same error. Fixed it by removing the comma and space here https://github.com/CloudBoost/cloudboost/blob/staging/services/cloudObjects.js#L397
