### ISSUE TITLE
Cluster registration failed

### ISSUE THREAD

**Issue by itsMagondu** [CloudBoost/cloudboost#246]
Hey! I have just installed Cloudboost on my Ubuntu 16 laptop. I experienced the issue here #245 and fixed it (I have commented on my fix). I am however now facing the issue below. Please assist
Redis: 4.0.1
Mongo: v3.4.7

```
Cluster registration failed.
{ Error: connect ECONNREFUSED 127.0.0.1:5555
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5555 }
```

**Comment by shubhamqweasd** [comment]
Hi @itsMagondu , this error is expected because CloudBoost uses an Analytics Engine which is supposed to be running on port 5555, but as of now that Analytics engine is closed source. So you can neglect this error for now, it wont affect CloudBoost Engine in any way.
