### ISSUE TITLE
Experience with Self hosting & limitations

### ISSUE THREAD

**Issue by mehdi-cit** [CloudBoost/cloudboost#280]
Hello all.
I'm looking into CloudBoost as it allows for selfhosting (It is mandatory for many clients keep their data in-house, so cloud is out of the question ).
My question is to the limitations of self-hosting cloud-boost apps. From reading the issues at https://github.com/CloudBoost/cloudboost/ it seems the only limitation is the dashboard that is not open-source.
Any other limitations ? How was your experience with self hosting and maintaining/scaling CloudBoost apps.
A quick note to CloudBoost team. We are our selves software developers and do understand the need to charge for our services. If we invest our time learning and using CloudBoost we'd want your team to thrive and do well. It's a win-win situation. I am just saying it's ok, even desirable that you do charge and earn good money out of CloudBoost. However, I respectfully ask you to be forthcoming about any known or expected hurdles down the line for people who adopt CloudBoost and host it them selves. 
What should one expect in terms of dev-ops, maintenance costs, performance issues pertaining to self hosting the open source version ...etc.
I hope to get a straight and clear answer :)
Thank you for your hard work. All the best 👍

**Comment by nawazdhandala** [comment]
Hi @mehdi-cit, 

Installing and managing CloudBoost yourself should be used for experimental / hobby projects and should not be used for production apps. It takes a lot to manage and scale the service. If you're using CloudBoost for production apps, check out our enterprise page (https://cloudboost.io/enterprise/demo)  and we'll help you to manage and host the service on your servers. 

If you're using CloudBoost for a hobby project. Check out our docker repo (https://github.com/cloudboost/docker) which contains a Docker Compose file that helps you to run the service on local / any server with one command. 

Let me know if this helps.

**Comment by mehdi-cit** [comment]
Thank you for the quick reply.
I am new to CloudBoost. I am using these free days to "shop" for self hosted solutions/alternatives. To be completely honest and clear. I do not want to spend too much upfront time only to find out this or that solution is not good for me.
I did check the enterprise page. It does not say much. Maybe you can clarify things for me. 
If I pick CloudBoost for a production app that must be self hosted by my client (I will do the installation and maintenance). Do you offer consultancy to help me achieve that per project basis. In such case how's you rate and how much time/effort/money would it take to have a production app for let's say a company that has few thousands users with tops a couple of hundreds using the system at any given time. I'd say, the load would be average where the system would not need to deal with more than a dozen "regular, single Join SQL queries" and a couple of writes per second.
Thank you in advance for bearing with me.

**Comment by nawazdhandala** [comment]
We offer annual maintenance contracts which includes maintenance, scale, upgrades and consulting / support. If you want to quickly get started, sign up for our free account and you can test the service as long as you want. That's the easiest and the quickest way to get started. 

Annual contracts starts with $500 / server / yr or $2500 / yr whichever is higher. 

Let me know if this helps.

**Comment by mehdi-cit** [comment]
That what was looking for! 
My understanding is that I pay you 500$/year per server or max $2500 / yr for any number of servers. With that I will get your help and assistance with my own dev/deployment/maintenance/scaling issues
From experience, such setup would result in "hand holding" at the beginning with many hours required, Then with time things will get much smoother (with additional apps etc..). I suppose you do take that into consideration and allow for some lee way in how the allocated hours for each customer of yours vary with time.
:) I will keep this close by while shopping around.
Have a nice day!

**Comment by nawazdhandala** [comment]
Sure, let us know. :)
