### ISSUE TITLE
Client SDK is not receiving notifications 

### ISSUE THREAD

**Issue by nomantintash** [CloudBoost/cloudboost#291]
I had implemented cloudboost open source on my server, on client side I am using cloudboost npm package. I had added observers on different tables on created update and delete, now the problem is after exact 10 notifications the client is not able to get notifications from cloudboost server, If I restart the client code it start receiving notifications. 
Urgent Help Required

**Comment by nawazdhandala** [comment]
Is this fixed?

**Comment by nomantintash** [comment]
@nawazdhandala  no, the actual problem is that client only received ten notifications only. Can you please identify what is the issue ?

**Comment by nawazdhandala** [comment]
Sure, I am investigating.

**Comment by nawazdhandala** [comment]
Can you please send me your code.

**Comment by nomantintash** [comment]
Okay yes sure we are using open source cloudboost server here is my observer 
`CB.CloudApp.init(config.cbUrl, config.appId, config.key);

let counter = 0;
var query = new helpers.CB.CloudQuery('printer');
query.equalTo('username',"ahmedroofi");
CB.CloudObject.on('printer', 'created', query, function(obj){
    logging.info("\n************ NOTIFICATION on Printer Update/Create *******************")
    logging.info(obj)
    counter = counter + 1;
    logging.info("\n************ END OF NOTIFICATION ********************* \n")
    logging.info ("Notifications count ", counter);
});`

and we are inserting record from python program by using curl commands, I hope this will help

**Comment by nawazdhandala** [comment]
Please send the curl command as well.

**Comment by nomantintash** [comment]
@nawazdhandala  here is the curl command

data = {‘document': {'username': 'ahmedroofi', '_type': 'custom', 'expires': None, '_isModified': True, '_modifiedColumns': ['createdAt', 'updatedAt', 'ACL', 'expires', 'username'], 'ACL': {'write': {'deny': {'role': [], 'user': []}, 'allow': {'role': [], 'user': ['all']}}, 'read': {'deny': {'role': [], 'user': []}, 'allow': {'role': [], 'user': ['all']}}}, '_tableName': 'printer'}, 'key': 'd545cbe3-b464-43e6-8b6e-c8e55cea9828'} 
url = http://192.168.1.8:4730/data/Test/printer
headers = {‘Content-type': 'application/json'}
data = json.dumps(data)
response = requests.put(url, data=data, headers=headers)

**Comment by nawazdhandala** [comment]
Thanks! I'll investigate this and get back. :)

**Comment by meer-online** [comment]
@nomantintash I believe that there is an error inside your code, which halts the notifications.

**Comment by meer-online** [comment]
I believe there is an error inside your code, the way you are adding observer on your printer object is wrong.

```
CB.CloudObject.on('printer', 'created', query, function(obj){
logging.info("\n************ NOTIFICATION on Printer Update/Create *******")
logging.info(obj)
counter = counter + 1;
logging.info("\n END OF NOTIFICATION ********************* \n")
logging.info ("Notifications count ", counter);
});`
```

**Comment by meer-online** [comment]
@nomantintash I believe there is a issue inside the code snippet your shared, You are passing 'query' parameter to the event listener on CloudObject whereas the 4 parameters that it actually takes are tableName, eventType, functionToFire(Your custom function to fire when the event occurs) and a callback (optional- Success/Error callback if the subscribe to event was successful / failed). so passing in a CloudQuery object does not make sense here.

So try replacing your event subscription code 
```
CB.CloudObject.on('printer', 'created', query, function(obj){
    console.log('printer Created : '+obj.get('name'));
    console.log("\n************ NOTIFICATION on Printer Update/Create *******************");
    console.log(obj);
    console.log("\n************ END OF NOTIFICATION ********************* \n");
    console.log("Notifications count ", counter);
    console.log("\n");
    counter = counter + 1;
});

```

with this snippet and test.

```
CB.CloudObject.on('printer', 'created', function(obj){
    console.log('printer Created : '+obj.get('name'));
}, { //callback
    success : function(){
      //subscribe success
    },
    error : function(err){
      //failed  
    }
});

```
Let us know if it works. However i'll do some more debugging to see why are you receiving actually 10 notifications on successful subscription whereas you should only be receiving one when the callback executes.

**Comment by muradakhter** [comment]
@meer-online your findings are interesting but I think the syntax is valid. At least according to the tutorial at https://tutorials.cloudboost.io/en/realtime/cloudobjectnotifications#Queriesovernotifications it is acceptable to pass in a query parameter as follows: 

var query = new CB.CloudQuery('Student');
query.equalTo('age',10);
//
CB.CloudObject.on('Student', 'created', query, function(obj){
    //only fires when age is equalTo 10.
});

**Comment by RajeelTintash** [comment]
We need to set the 

query.limit

The default value is 10 for CloudQuery.

so it will only return 10 results.

**Comment by nomantintash** [comment]
Yes I have seen the limit on cloud boost server last night, but at that
time I was not sure how it is linked notifications.

Regards
Noman Maqsood
Server Engineer

**Comment by nomantintash** [comment]
@meer-online , @muradakhter  is right, we pass query to the function when we are looking for notifications to be sent on specific condition

**Comment by meer-online** [comment]
@muradakhter yes, you are right. I missed that part of the documentation the first time, However was able to figure that out later. @RajeelTintash is right that the issue occured because of the limit on CloudQuery object.

**Comment by nawazdhandala** [comment]
Yes, I think the problem is with query.limit. :) Let me know if this helps.

**Comment by nomantintash** [comment]
@nawazdhandala it is working fine for us, we will get in touch with you if we face any issue. Thank you
