### ISSUE TITLE
Standalone Install Guide

### ISSUE THREAD

**Issue by rjpalermo1** [CloudBoost/cloudboost#30]
Hello, I've been evaluating many open source backends to 'package' a parse replacement and would like to look at cloudboost but cannot find....anywhere....standalone installation instructions.  Docker is cool and all but not a be-all, end-all.  

I see NPM and BOWER install packages but nothing on server/redis/mongo configurations...

Gotta move on for now hoping for a positive replay so I can come back and give your backend a look.

**Comment by nawazdhandala** [comment]
We're working on it.  :)

**Comment by nawazdhandala** [comment]
This is done! :) I have this in the development branch. Should be pushed to master during next deployment.
