### ISSUE TITLE
Add Columns with Master key

### ISSUE THREAD

**Issue by Mhd-Khaled** [CloudBoost/cloudboost#305]
Hi, 
I am using open source cloudBoost.io on my own laptop.
I have faced a problem with adding new columns to tables.
when I add and save the new column using Master key it returns a **table object** including  the new column successfully.
but when I try to get the new column of that table **using getColumn()**  again,  the new added column won't return with the response. and the server return status code 500.

I have just tried javescript and nodeJs SDK.

any help please?

**Comment by nawazdhandala** [comment]
Can you please send me the code please so I can investigate?

**Comment by Mhd-Khaled** [comment]
I have figured out the problem, unfortunately, it was a bug in my code.
Thanks for replay, **I really appreciate it.**
**Thanks a lot.**
