### ISSUE TITLE
Make CloudQuery substring API method case insensitive

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/cloudboost#31]

**Comment by nawazdhandala** [comment]
Thank you for letting us know about this. This seems like a nice feature to have. :)

**Comment by gabrielAnglada** [comment]
Any time prevision?

Thanks!

**Comment by nawazdhandala** [comment]
About 5 days.

**Comment by gabrielAnglada** [comment]
Any update on this? I would need it to be fixed as soon as possible. Users are not finding each other in m app

**Comment by nawazdhandala** [comment]
We're on it right now. This should be done by the end of the day today.

**Comment by nawazdhandala** [comment]
use query.substring('column','value',true);

**Comment by gabrielAnglada** [comment]
It works perfectly!
