### ISSUE TITLE
CloudQuery orderBy issue when lowercase/uppercase

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/cloudboost#32]
I have got a list of elements with a column "title" of type text. When ordering these elements by title, treats different titles starting by uppercase than lowercase. Here is an example:

I have got this list:

`Lemon, Apple, avocado, Banana`

The expected result of CloudQuery.orderByAsc('title') is:

`Apple, avocado, Banana, Lemon`

But the result is:

`Apple, Banana, Lemon, avocado`

Thanks!

**Comment by nawazdhandala** [comment]
Noted. :)

**Comment by gabrielAnglada** [comment]
Any time prevision?

Thanks!

**Comment by nawazdhandala** [comment]
About 5 days. :)

**Comment by gabrielAnglada** [comment]
Any update on this?

**Comment by nawazdhandala** [comment]
We're looking into this right now.

**Comment by nawazdhandala** [comment]
This unfortunately is not supported by MongoDB (which is our storage backend).
