### ISSUE TITLE
Add ElasticSearch support for latest version. 

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/cloudboost#34]

**Comment by nawazdhandala** [comment]
Not required.

**Comment by pfurini** [comment]
Hi, sorry to bother in an old closed issue, but why `elasticsearch` is currently included in package.json and declared as a node in `config.json`?
Is it safe to get rid of that dependencies, as it seems ES is not used anywhere in the codebase?

**Comment by nawazdhandala** [comment]
Yes. I think that's correct. We'll get it done. :)
