### ISSUE TITLE
API to display the app list

### ISSUE THREAD

**Issue by darknblack** [CloudBoost/cloudboost#360]
Sometimes, I forgot the apps that i have created and it would be very beneficial to have an API that I can be use to display the list of created applications.

**Comment by Blacktoviche** [comment]
I was looking for the same things as I'm building small cloudboost dashboard for test
I checked the code I found there is a function for getting all apps in /cloudboost/services/app.js
But they are not exposing this function for REST API
So I added new function  in /cloudboost/api/app/App.js 

const listApp = async (req, res) => { 
  const body = req.body || {};
  const { sdk = 'REST', secureKey: parsedSecureKey } = body;
  if (config.secureKey === parsedSecureKey) {
    try {
      const appList = await appService.getAppList();
      return res.status(200).json({
        status: 'Success',
        appList,
      });
    } catch (error) {
      return res.status(500).send({
        status: 'Error',
        error,
      });
    }
  } else {
    return res.status(401).send({
      status: 'Unauthorized',
    });
  }
};`
`
Also add the rest endpoint for this function inside module.export = (app) => etc.. in the same file
`  //List App
  app.get('/app/list', listApp);`


Now you can call http://ip:4730/app/list  with your securekey 
You will get a list of all apps you have created

**Comment by darknblack** [comment]
> I was looking for the same things as I'm building small cloudboost dashboard for test
> I checked the code I found there is a function for getting all apps in /cloudboost/services/app.js
> But they are not exposing this function for REST API
> So I added new function in /cloudboost/api/app/App.js
> `const listApp = async (req, res) => { const body = req.body || {}; const { sdk = 'REST', secureKey: parsedSecureKey } = body; if (config.secureKey === parsedSecureKey) { try { const appList = await appService.getAppList(); return res.status(200).json(appList); } catch (error) { return res.status(500).send({ status: 'Error', error, }); } } else { return res.status(401).send({ status: 'Unauthorized', }); } };`
> Also add the rest endpoint for this function inside module.export = (app) => etc.. in the same file
> ` //List App app.get('/app/list', listApp);`
> 
> Now you can call http://ip:4730/app/list with your securekey
> You will get a list of all apps you have created

Thank you so much for this =)
