### ISSUE TITLE
Multiple versions of an app

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#38]
To allow developers to work on future or customized versions of the same app. Each version with staging/production modes (see other enhancement request).

**Comment by nawazdhandala** [comment]
Good idea, but this will over complicate things for the rest of  the people. Dont you think?

**Comment by MicheleLonghi** [comment]
I agree that this is a complication to many but for complex projects roadmaps is a great addition: you have a released version and want to start with a major release having a huge impact to data structure; you create a name a new version starting from the current one. For the rest the versions are independent each other; client side, during app initialization all you need to do is specify along the key ad id, the version identifier to use, such `app.init(appId, appKey, "v2")`.
A simpler solution could be a sort of export/import mechanism between apps.

**Comment by nawazdhandala** [comment]
Are the version numbers for both Data + Schema or just the data.

**Comment by MicheleLonghi** [comment]
When creating the new version would be nice to have three options:

- [ ] Empty (new version from scratch but in the same app
- [ ] Copy structure only (no data)
- [ ] Copy everything (structure, data, certificates, etc)

**Comment by nawazdhandala** [comment]
This can be done. :)

**Comment by MicheleLonghi** [comment]
Eh eh. Is just a copy; after that, the version are independent. Another think is to maintain structures between versions, migrations and so on...not the purpose of this topic.

**Comment by nawazdhandala** [comment]
I think this can be done but with different apps. The only thing I can think of is, People will abuse this by  "Oh, I'm running out of the API limit?", "Let me copy and create a new app and change my app keys"

**Comment by MicheleLonghi** [comment]
Indeed I was speaking about data structure, not data content.
