### ISSUE TITLE
Signup confirmation for user

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#40]
Actually we have to implement an in-house mechanism to send email confirmation for user signup. Would be nice to have in right in CB.

1. After signup the user record is in unconfirmed state
2. A mail (customizable in CB dashboard) is automatically sent to the user email
3. The user select a confirmation like that opens a default or a customized URL (this step is very important)
4. The user state become confirmed

Some notes:
During unconfirmed state the user should be able to login. Is up to the app to determine that and behave the desired way. This is important because some system force the user to login after confirmation and that's not always a good experience.

In regard to point 3, the default could just point to a confirmation web page, stating that the account is confirmed. The custom url could have a custom schema or a deep link in order to open directly the client app.

**Comment by nawazdhandala** [comment]
This is a good one. :) We'll get to work on this.

**Comment by nawazdhandala** [comment]
This is done. We'll be launching this by today. I'm closing this issue.
