### ISSUE TITLE
Send email to channels 

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#41]
The possibility to publish emails to channels, non only push messages.

**Comment by nawazdhandala** [comment]
Emails exist in the user table right now. Do you want channels column in the user table?

**Comment by MicheleLonghi** [comment]
No, I meant a way to send email from CB, like send for push notifications

**Comment by nawazdhandala** [comment]
Hmm.... but how do we know which user / email is in which channel.

**Comment by MicheleLonghi** [comment]
Something like subscribe/addToChannel
