### ISSUE TITLE
Reg Search and Query: how to search on relations

### ISSUE THREAD

**Issue by rusamgr8** [CloudBoost/cloudboost#47]
One of my object is having field which has relation of other object. So when I want to make search on that field how should I search as in that field I will just have IDs

with this :  query.equalTo('obj.relatedProp","value"); I can only search on `obj._id`

I also want to make search on obj.name

Please help me with this

**Comment by nawazdhandala** [comment]
We're working on the relations feature. You'll be see'ing simple relations and even advanced relations being build in the coming few weeks. Thank you for the heads up.

**Comment by rusamgr8** [comment]
Thank you..Please let us know once done..as required this feature urgently

**Comment by nawazdhandala** [comment]
This should be done in about 10 days from now.

**Comment by rusamgr8** [comment]
Hi Team, whats the status on this issue.

**Comment by nawazdhandala** [comment]
5 more days please. We're sorry for the delay.

**Comment by rusamgr8** [comment]
Hi Team, any updates. This is affecting my release plan. Please fix it up asap.
Thank you.

**Comment by nawazdhandala** [comment]
Can you get this done using multiple queries for now.
