### ISSUE TITLE
API calls from dashboard not computed in API Quota

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/cloudboost#48]
Sometimes it is needed to perform so many actions in clouadboost dashboard. Maybe it is comprehensible that this api calls are not computed.

**Comment by nawazdhandala** [comment]
I'm sorry, this might not be possible. Dashboard uses the same API as apps.

**Comment by gabrielAnglada** [comment]
I know but, there is no way to send different heders or something to make a distinction?

**Comment by nawazdhandala** [comment]
Hmm... If that's the case, then devs would hack the SDK and write those headers to all the API calls.
