### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by kethan** [CloudBoost/cloudboost#50]
how to go to the dashboard??.. for docker installation.... how can i create apps in dashboard?

**Comment by nawazdhandala** [comment]
Open Source CloudBoost / CloudBoost on docker does not include dashboard. You can use the hosted and managed offering at CloudBoost.io if you need a Dashboard to visualize your app data. Alternatively, You can use Robo Mongo / MongoVUE to connect to your database to visualize your app data when you're using Docker
