### ISSUE TITLE
JS Client init CORS error

### ISSUE THREAD

**Issue by kethan** [CloudBoost/cloudboost#51]
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute

Please help me i am unable to CB.CloudApp.init call this function

PS: I am totally newbie.

**Comment by nawazdhandala** [comment]
What's your code?

**Comment by kethan** [comment]
CB.CloudApp.init('http://192.168.5.78:80/', 'sample', '2ea31af9-c37e-47a3-968b-204fe743a2ec');

**Comment by kethan** [comment]
<script src="https://cloudboost.io/js-sdk/cloudboost.js"></script>
<script>
CB.CloudApp.init('http://192.168.5.78:80/', 'sample', '2ea31af9-c37e-47a3-968b-204fe743a2ec');
</script>

**Comment by kethan** [comment]
Someone kind enough to answer me?

**Comment by nawazdhandala** [comment]
Let me test and get back. :)

**Comment by kethan** [comment]
Any input?

**Comment by nawazdhandala** [comment]
Working on this. 2 more days please.
