### ISSUE TITLE
Duplicate app structure

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#59]
Publishing several branded apps with each one a separate CloudBoost app it's a real problem, since we have to manually recreate the data structure.
I suggest a command to duplicate an app, without the content (structure only).

**Comment by nawazdhandala** [comment]
Okay, We'll get this done. :)

**Comment by MicheleLonghi** [comment]
We have to produce several branded apps with the same data structure and it is a nightmare to do it by hand.
