### ISSUE TITLE
Tutorial Setup Credentials on Docker (Push, Email, Social Login)

### ISSUE THREAD

**Issue by mymanga** [CloudBoost/cloudboost#60]
Since the docker version doesn't have a dashboard, can we please get tutorials on how to setup API keys and certificates for push messaging, social login and email services

**Comment by nawazdhandala** [comment]
Thank you for your feedback .We're working on it. :)

**Comment by nawazdhandala** [comment]
Check this out here : https://github.com/CloudBoost/cloudboost/tree/master/docs/app-settings
