### ISSUE TITLE
Unable to delete files from dashboard

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#61]
I have a list attribute with several files in it. From the dashboard I delete them and they disappear; refreshing the table, they're still there.

It's worth to mention that these files were uploaded from client. With files uploaded directly from the dashboard, everything is fine. Trying to access these files from client with their urls, I get error 500.

_(app id: hpqorxfmqdbb, table: Event, record id: B5LO0RZz)_

**Comment by RTBathula** [comment]
Javascript SDK and dashboard is fine , i will move this issue to swift SDK

**Comment by MicheleLonghi** [comment]
From the dashboard I still cannot delete the files

**Comment by MicheleLonghi** [comment]
Now I deleted and recreated the column Files (it's a List) and the files are gone of course.
The problem is that adding files to the newly created column, they disappear when I refresh the table - no use of any SDK.

**Comment by nawazdhandala** [comment]
Let us invstigate this tomorrow and get back.

**Comment by MicheleLonghi** [comment]
Still present

**Comment by MicheleLonghi** [comment]
You never solved this.

**Comment by MicheleLonghi** [comment]
Three months for a basic feature

**Comment by nawazdhandala** [comment]
Fixed.
