### ISSUE TITLE
Better support for custom QueueMessage on Dashboard

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#62]
* Truccate object on list
* Editing capabilities, like object editing in table browser

<img width="1020" alt="schermata 2016-06-06 alle 12 37 55" src="https://cloud.githubusercontent.com/assets/867473/15819491/bda99660-2be3-11e6-8df2-ab2a503254e1.png">
<img width="589" alt="schermata 2016-06-06 alle 12 39 57" src="https://cloud.githubusercontent.com/assets/867473/15819497/c9e08cd6-2be3-11e6-993c-0f019325e2e9.png">

**Comment by nawazdhandala** [comment]
Done!
