### ISSUE TITLE
Initial authentication settings default values in dashboard are ignored

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#66]
In authentications settings for app in the dashboard the default values are opposite at what showed.
As an example: Enable Sign up Email is off by default, but the signup email is sent. I have to switch on and off again to make it behave correctly.

**Comment by MicheleLonghi** [comment]
I see that even disabling Enable Sign up Email, the mail is sent

**Comment by nawazdhandala** [comment]
Done!
