### ISSUE TITLE
Missing link in password recovery mail

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#69]
The link has the following content:
<a class="link"></a>
No link to click into the mail.

![preview-chat-img_1445](https://cloud.githubusercontent.com/assets/867473/16012637/a68a2524-318a-11e6-8145-6225c9b8d4cb.PNG)

**Comment by MicheleLonghi** [comment]
The link is still not visible. Do we have to regenerate our template?

**Comment by nawazdhandala** [comment]
Add <a class="link">Reset your password</a> to your HTML template. :)
