### ISSUE TITLE
Duplicate CloudObjects in List

### ISSUE THREAD

**Issue by RTBathula** [CloudBoost/cloudboost#7]
i added 2 same  cloudObjects in list.

and after when i form normal Find Query,
cloudObject is returning TWO same records in the LIST

**Comment by kbuhiire** [comment]
Hey please can you provide more information about the issue screenshoots would be more helpful

**Comment by nawazdhandala** [comment]
Hey Ken, 

This issue is about the list of relations. Let me give you an example : 

```
var parent = new CB.CloudObject('Parent');

var child = new CB.CloudObject('Child');

parent.set('children',[child,child]);

parent.save().then(function(parent){
console.log(parent.get('children')); //here it gives you [child,child] which is correct. But same objects cannot be added twice in an array. It should ideally return [child]
});

```

**Comment by RTBathula** [comment]
Fixed
