### ISSUE TITLE
Dashboard issues on Mac and iPad 

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#70]
In various screens of the dashboard various kinds of issue are present. 
On Mac they problems are in Safari Chrome and Firefox. 

Some examples:
- in tables sometimes it is not possible to scroll horizontally (have to reload the page)
- settings authentication shows an empty screen. After reloading page the form is shown but it is impossible to edit the mail template because pressing backspace causes to return to the previous page
- push notification send form is badly formatted

There are many more visual issues. It is a general compatibility problem.

**Comment by GheberEl** [comment]
Hi, this issue is still present, especially all three example points, both on Safari and Chrome (for Mac). Very frustrating.

**Comment by MicheleLonghi** [comment]
Almost unusable in some circumstances

**Comment by gabrielAnglada** [comment]
+1

**Comment by MicheleLonghi** [comment]
Still not working

**Comment by nawazdhandala** [comment]
We're working on a completely new portal.
