### ISSUE TITLE
Custom email sender

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#72]
Replace hello@cloudboost.io with a custom email address.

**Comment by nawazdhandala** [comment]
YOu can do this in the app settings. Check the email section of app settings.

**Comment by MicheleLonghi** [comment]
In order to change email settings you have to enter Mandrill or Mailgun keys.

**Comment by nawazdhandala** [comment]
Yes. That is correct, because we're not authorized to send emails from your domain directly. You verify your domain with mandrill / mailgun and have those API keys in CB.

**Comment by MicheleLonghi** [comment]
Why not provide smtp settings?

**Comment by nawazdhandala** [comment]
Not recommended. Emails will be marked as spam if sent from the same IP. Most of our customers use Mailgun (That's free)

**Comment by MicheleLonghi** [comment]
It's up to the customer in that case. Actually with BaasBox we send confirmation and password reset emails from the same SMTP (managed from Dreamhost.com) and we don't have spam problems.

**Comment by nawazdhandala** [comment]
We actually implemented SMTP first, but google cloud (where CB is hosted) blocked port 22. So, we switched to email providers.

**Comment by MicheleLonghi** [comment]
We'll go for the moment on Mailgun but frankly I don't like to depend on multiple providers for a single service, considering the fact that we'll be using it only for recovery emails.

**Comment by nawazdhandala** [comment]
Yes, Emails are a huge thing and they do it way better than we ever could. So, this is why we give you third party integrations. Mixpanel, Segment.io, Loggly more coming up soon.
