### ISSUE TITLE
Customize restore password page

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#73]

**Comment by MicheleLonghi** [comment]
Now the restore page shows always  a Login button. 
For native all with custom login, this is interface is misleading to the user. 
I propose a custom text with a custom URL, typically set ti a custom scheme (eg myapp://) so that the original caller app is reopened. 
As it is now is useless.

**Comment by MicheleLonghi** [comment]
It is marked as closed but a useless login button is not the solution.

**Comment by nawazdhandala** [comment]
I'm fixing this. Expected launch by Monday.

**Comment by nawazdhandala** [comment]
Done. Deploy pending.
