### ISSUE TITLE
Email templates not displaying on dashboard

### ISSUE THREAD

**Issue by gabrielAnglada** [CloudBoost/cloudboost#76]
I cannot edit "reset password" email template because templates has dissappeared.

Thanks!

**Comment by nawazdhandala** [comment]
Can you resave them and cehck if they are visible.

**Comment by gabrielAnglada** [comment]
I have just saved and refreshed but no effect. I have mailgun provider configured if it helps.

**Comment by nawazdhandala** [comment]
Okay, I'm checking this right away.

**Comment by gabrielAnglada** [comment]
Any advances on this?

**Comment by gabrielAnglada** [comment]
Hi, I need this to be fixed as ASAP please. Many users are trying to recover their password and there is something worng in the email template and link is not displayed.

Thanks!

**Comment by gabrielAnglada** [comment]
ping!

**Comment by nawazdhandala** [comment]
Does it display on windows?
