### ISSUE TITLE
Unable to send Push campaign

### ISSUE THREAD

**Issue by GheberEl** [CloudBoost/cloudboost#77]
Hi,
on the Settings of Push notifications I set properly both iOS and Android, not for Windows, because we not have an app for Windows phone os, obviously ;-)

**First try**
Set title and message and send.
**First error**
![schermata 2016-06-30 alle 18 12 13](https://cloud.githubusercontent.com/assets/7791923/16496011/2c1ed320-3ef0-11e6-89f6-66824ba6d030.png)
I assume that error is related with missing credentials of Windows Push Notifications.

**Second try**
Set title, message and select my audience.
**Second error**
![schermata 2016-06-30 alle 18 39 05](https://cloud.githubusercontent.com/assets/7791923/16496390/f23fa0ba-3ef1-11e6-941f-7c5f57042e1f.png)

The filter of device OS not recognize my iPhone.
![schermata 2016-06-30 alle 18 09 06](https://cloud.githubusercontent.com/assets/7791923/16496239/49efc610-3ef1-11e6-825c-8a457ebc56f3.png)

Note: fields Title and Message are emptied after you press Send.

**Comment by nawazdhandala** [comment]
I'm checking this out. :)

**Comment by GheberEl** [comment]
seems work fine now. thanks.
but those two emoji before title in the push notification will be there forever, or with the app in production they will disappear?
