### ISSUE TITLE
Full push dictionary in send push Create Push Campaign panel

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#78]
In order to test all the notification functionalities, as sound, badges and app-specific parameters, would be useful to have a dictionary editor, in alternative to title and message fields.

**Comment by nawazdhandala** [comment]
@MicheleLonghi I think you fixed this up. Let me know if I'm wrong.

**Comment by MicheleLonghi** [comment]
I fixed in server, enabling it to send custom dictionary for iOS and Android. What is missing is the test UI into Dashboard.
Server documentation has to be updated, but it uses the "custom" key in push data dictionary.

**Comment by nawazdhandala** [comment]
Okay, Deployment pending.
