### ISSUE TITLE
Callback URL after restoration password

### ISSUE THREAD

**Issue by GheberEl** [CloudBoost/cloudboost#80]
For us, with an app that doesn't use your authentication web page is a bit confusing and useless for users, when they do not return in the app after saving a new password.

**Comment by MicheleLonghi** [comment]
+1

**Comment by MicheleLonghi** [comment]
@nawazdhandala this is pretty urgent

**Comment by nawazdhandala** [comment]
Got it, I'm on it. :)

**Comment by nawazdhandala** [comment]
Should be done by EOD.

**Comment by nawazdhandala** [comment]
Done. Deploy pending.
