### ISSUE TITLE
ACL is not working 

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/cloudboost#87]

**Comment by nawazdhandala** [comment]
with JavaScript SDK?

**Comment by MicheleLonghi** [comment]
No. with swift SDK.

**Comment by MicheleLonghi** [comment]
Issue #12 - About 6 months ago.

**Comment by MicheleLonghi** [comment]
After days of work we discovered that ACL can be set only during object creation and not in subsequent updates. Nice.

**Comment by nawazdhandala** [comment]
Do you add ACL into _modifiedColumns?
