### ISSUE TITLE
question: how does offline/online sync work?

### ISSUE THREAD

**Issue by beebase** [CloudBoost/cloudboost#88]
Is there a code snippet somewhere that demonstrates how to save/handle mobile client data when it goes off/online?

**Comment by nawazdhandala** [comment]
This feature is under active development right now and should be out on JavaScript SDK in a couple of weeks. Which SDK are you using right now?

**Comment by beebase** [comment]
Vue.js with cordova for ios and android

**Comment by nawazdhandala** [comment]
Awesome! I’ll let you know when we have that running. :) 

 

Regards,

Nawaz Dhandala.
