### ISSUE TITLE
Push notification support. 

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/cloudboost#9]

**Comment by gabrielAnglada** [comment]
Are you going to integrate with a third party like pushwoosh?

**Comment by nawazdhandala** [comment]
No, We're building a custom push notification service. :)

**Comment by gabrielAnglada** [comment]
Wow, want to see it OO

**Comment by nawazdhandala** [comment]
2 more weeks. It should be done. :)

**Comment by gabrielAnglada** [comment]
Is this already implemented? Are you working in documentation? I cannot wait to see it working.

**Comment by nawazdhandala** [comment]
No, We're on this. Please expect a 2 week turn around.

**Comment by nawazdhandala** [comment]
We're working on the SDK support, backend is built.

**Comment by gabrielAnglada** [comment]
Have you planned to integrate this with ionic/cordova?

**Comment by nawazdhandala** [comment]
Yes. First we plan to launch this on iOS, Windows and Android and then we're going to get this thing up for Ionic.:)

**Comment by gabrielAnglada** [comment]
Any estimation of when it would be ready for ionic?

**Comment by nawazdhandala** [comment]
Thank you for letting us know about this. This should take about a end of next week to finish.

**Comment by gabrielAnglada** [comment]
Hi Nawaz! How is it going? Any prevision to use Push for IOS and Android? I'm waiting for this feature to launch the next release of my app

**Comment by nawazdhandala** [comment]
This should be launched this tuesday. :)

**Comment by gabrielAnglada** [comment]
Are you also working in javascript api to send push notifications?

**Comment by nawazdhandala** [comment]
Yes. We'll be building PhoneGap / Ionic / Cordova support very soon after we launch this.

**Comment by gabrielAnglada** [comment]
In fact, I would like to test your development with the plugin that I commented you (https://github.com/phonegap/phonegap-plugin-push) Maybe, you don't need to develop any integration for ionic / cordova. 

The question is, Will be available an api method for javascript like: 

`CB.Push.send([devices], content)`

I think, all the other code will work with the plugin. I will mantain you informed.

Thanks!

**Comment by gabrielAnglada** [comment]
Hi Nawaz! Any news about this?

Hava a nice weekend!

**Comment by nawazdhandala** [comment]
Sorry, for the delay. Push Notification for Windows and Android should be launched today. :) Let me know if you need any more details.

**Comment by gabrielAnglada** [comment]
And When it is going to be ready for IOS?

Thanks!

**Comment by nawazdhandala** [comment]
I'm guessing by end of this month or first week of May.

**Comment by gabrielAnglada** [comment]
How can it be? You said to me it was going to be ready this tuesday and now we are talking about next month? What has happened?

It is a very bad new for my app :(

**Comment by nawazdhandala** [comment]
Hi Gabriel, 

I'm sorry if we misunderstood each other. We're still in the process of building the iOS (Swift) SDK. We have ,NET and Android ready. iOS is scheduled to launch by the end of this month. Tuesday was for both Android and .NET. 

Let me know if this helps.

**Comment by nawazdhandala** [comment]
You can use a company like OneSignal is you need something urgent.

**Comment by gabrielAnglada** [comment]
Don't worry, I will integrate oneSignal. It was the original idea, but I was waiting for you.

Thanks again!

**Comment by mymanga** [comment]
Similar to this one https://github.com/otmezger/parse-push-plugin made for parse , built from official phonegap-push-plugin. The cordova plugin will have the Google, Apple, Windows SDKs for cloudboost. Server settings are added to app javascript `(CB.CloudApp.init 'YOUR APP ID', 'YOUR APP KEY', 'SERVER URL');`  and forwared on to SDK during build.

**Comment by nawazdhandala** [comment]
Thanks for letting us know. We're still building Push Notifications for iOS and Phonegap.

**Comment by mymanga** [comment]
Any update on cloudboost and phonegap/cordova/ionic integration

**Comment by steveharman** [comment]
I'd like an update on the phonegap / Cordova progress too please.
