### ISSUE TITLE
Expires still immediately removed

### ISSUE THREAD

**Issue by hdriqi** [CloudBoost/cloudboost#94]
I try to use expires, but it immediately removed when I try to fetch the data

this issue https://github.com/CloudBoost/cloudboost/issues/5 said that it is already fixed, but still the data removed immediately although it is not the time it should expired.

**Comment by nawazdhandala** [comment]
Thank you for posting the issue. We'll get it fixed ASAP.

**Comment by hdriqi** [comment]
please update here if it is already fixed. thanks

**Comment by nawazdhandala** [comment]
I think we're done, but the build breaks right now. I'll look into it first thing tomorrow my morning and update.

**Comment by hdriqi** [comment]
is it already fixed?

**Comment by nawazdhandala** [comment]
Few more hours and we're done. Apologies for the delay.

**Comment by nawazdhandala** [comment]
Done!
