### ISSUE TITLE
Cloudboost storage 500 error code

### ISSUE THREAD

**Issue by hdriqi** [CloudBoost/cloudboost#97]
I just try the cloudboost storage and turns out after successfully uploading the file, I can not access the provided URL. The server respond with 500 error code and unauthorized. I also do not see any storage file in my dashboard.

I am pretty sure that my file is uploaded successfully cause the result gives me the id, url, and etc.

**Comment by nawazdhandala** [comment]
We dont see this issue in production. Can you please check.
